# Generated by Django 5.0 on 2025-12-03 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('forms_app', '0002_add_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'form_templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('mcq', 'Multiple Choice'), ('text', 'Text Response')], max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_questions', to='forms_app.formtemplate')),
            ],
            options={
                'db_table': 'template_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TemplateOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_text', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_options', to='forms_app.templatequestion')),
            ],
            options={
                'db_table': 'template_options',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FormAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_allocations', to='core.course')),
                ('feedback_form', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation', to='forms_app.feedbackform')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_allocations', to='forms_app.teacher')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='forms_app.formtemplate')),
            ],
            options={
                'db_table': 'form_allocations',
                'ordering': ['-allocated_at'],
                'unique_together': {('template', 'teacher', 'course')},
            },
        ),
    ]
